### ISSUE TITLE
Spaces sometimes have no name (`title` key in json file)

### ISSUE THREAD

**Issue by TheBikramLama** [neurokitti/Arc_Palette#3]
```
-C:\...\main.py:24: SyntaxWarning: invalid escape sequence '\d'
  display_img = Image.open("resources\dot_pad.png") # add an arg later
-C:\...\main.py:170: SyntaxWarning: invalid escape sequence '\g'
  image.save('resources\gradient_wallpaper.png')
-C:\...\main.py:171: SyntaxWarning: invalid escape sequence '\g'
  self.set_wallpaper('resources\gradient_wallpaper.png')
-C:\...\main.py:252: SyntaxWarning: invalid escape sequence '\i'
  root.iconbitmap('resources\icon.ico')
Traceback (most recent call last):
  File "C:\...\main.py", line 249, in <module>
    arc_api = arc_API()
              ^^^^^^^^^
  File "C:\...\Arc_API\Arc_API.py", line 31, in __init__
    self.parse_spaces()
  File "C:\...\Arc_API\Arc_API.py", line 66, in parse_spaces
    "space_name":i['title'],
                 ~^^^^^^^^^
KeyError: 'title'
```

Python version: Python 3.12.5

**Comment by StudioMovieGirl** [comment]
nuh uh it works

**Comment by StudioMovieGirl** [comment]
edit: issue is that when running the code for the first time arc should be closed

**Comment by jacksonb2021** [comment]
This issue arises because a single backslash followed by certain characters "\n, \d. \t..." register as different functions.

**Comment by MrM8HDi** [comment]
i have this exact problem
i tried with arc being closed or open, no difference

```
Traceback (most recent call last):
  File "E:\Apps\Arc_Palette\main.py", line 217, in <module>
    arc_api = arc_API()
              ^^^^^^^^^
  File "E:\Apps\Arc_Palette\Arc_API\Arc_API.py", line 39, in __init__
    self.parse_spaces()
  File "E:\Apps\Arc_Palette\Arc_API\Arc_API.py", line 69, in parse_spaces
    "space_name":i['title'],
                 ~^^^^^^^^^
KeyError: 'title'
```
